[package]
name = "db_migraiton"
version = "0.1.0"
authors = ["SaiUmeshDhanewar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.17.0"
snafu = "0.6.2"